#+LATEX_HEADER: \usepackage[margin=0.5in]{geometry}
#+OPTIONS: toc:nil

#+HUGO_BASE_DIR: /home/shane/var/smulliga/source/git/mullikine/codecraft-dunedin.github.io
#+HUGO_SECTION: ./en/posts

#+TITLE: Next up on CodeCraft...
#+DATE: <2021-02-17>
#+AUTHOR: Chris Mein
#+KEYWORDS: update

*Hi everyone*

We had a great first meeting on the 2nd of February and for me
personally it was great to get back to a meeting in person!

So a big thanks to Kit, Ina and Nick for speaking.

Kit spoke about his experience trying to update a large Angular JS web
application to React whilst not impacting service 'too much' using
Single SPA ([[https://single-spa.js.org/]]). Maybe not for every project
but the discussion showed a few of the group using this technology for
various purposes.

Ina talked about her experience as a non-technical person creating the
NZ Secret Santa App. Built using Knack ([[https://www.knack.com/]] -
online database) and Integromat ([[https://www.integromat.com/]] -
workflow processing) it was cool to hear how the project was executed.
Adults still like achievement badges evidently.

Nick spoke about running Taint Analysis on a PHP project using Psalm
([[https://psalm.dev/]]). As usual when Nick is describing security
holes I was listening whilst thinking over my latest code. Really
interesting though as having these types of checks within our IDEs might
come in time.

I would finally like to ask everyone to once again start RSVP'ing to
meetings if at all possible. It really helps to do this as it is easier
to invite speakers along if we know there will be a good audience.

*~Chris*

We'll also be doing our best to try and get these talks on this website.
We will be experimenting with different ideas and such, so please bare
with us while we develop CodeCraft Dunedin website into something that's
educational for everyone. ~*Mike*
